In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5])
b=np.array([2,3,4])

print("shape a:{}".format(a.shape)) #shape: To get the dimensions of the array.
print("ndim {}".format(a.ndim))#ndim: To find out how many dimensions the array has.
print("size {}".format(a.size))#size: To determine the total number of elements in the array.
print(f"dtype {a.dtype}")#dtype: To check the data type of the elements in the array.
print(f"itemsize {a.itemsize}")#itemsize: To find out how much memory each element takes.
print(f"data {a.data}")#data: To access the raw data buffer of the array.

shape a:(5,)
ndim 1
size 5
dtype int64
itemsize 8
data <memory at 0x000002DBA890E980>


In [20]:
a1 = np.array([[2, 3, 4, 5],
               [1, 4, 7, 6]])
a2 = np.array([[1, 1, 1], [1, 1, 1]])

# Slicing the array
sliced_arr = a1[:2, :2]
print("Sliced Array:")
print(sliced_arr)


Sliced Array:
[[2 3]
 [1 4]]


In [4]:
index_arr=a1[[1,1],[2,1]]
print(index_arr)

[7 4]


In [5]:
arr=np.array([[25,64],[89,36]])
print(arr.sum())

214


In [6]:
#To compute the square root of each element in a NumPy array.

print(np.sqrt(arr))

[[5.         8.        ]
 [9.43398113 6.        ]]


In [7]:
#To obtain the transpose of a NumPy array.

print(arr.T)

[[25 89]
 [64 36]]


In [8]:
#perform matrix multiplication between two 2D arrays.

b1=np.array([[2,3],[4,5]])
b2=np.array([[5,6],[7,8]])
matrix_multi=np.dot(b1,b2)
print(matrix_multi)

[[31 36]
 [55 64]]


In [9]:
#indicate that not all elements in the array are True, 
#and only the second column contains all True values.

bool=np.array([[True,True],[False,True]])
print("all() with axis none",np.all(bool))
print("all() with axis 0",np.all(bool,axis=0))

all() with axis none False
all() with axis 0 [False  True]


In [10]:
#arange(): Generates a sequence of numbers.
temp=np.arange(9)
print(temp)

#reshape(): Changes the shape of an array without changing its data.
re=temp.reshape(3,3)
print(re)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [11]:
#it extracts the first and second columns from the array

print(np.take(re,[0,1],axis=1))

[[0 1]
 [3 4]
 [6 7]]


In [12]:
x=np.array([[12,23],[23,34]])
y=np.array([[56,67],[78,89]])
z=np.array([[32,43],[54,65]])

v=np.vstack((x,y,z)) #vstack(): Stacks arrays vertically (along rows).

h=np.hstack((x,y,z))#hstack(): Stacks arrays horizontally (along columns).

print("vstack:",v)
print("hstack:",h)

vstack: [[12 23]
 [23 34]
 [56 67]
 [78 89]
 [32 43]
 [54 65]]
hstack: [[12 23 56 67 32 43]
 [23 34 78 89 54 65]]


In [14]:
#hsplit(): Splits an array horizontally (along columns).
h_split=np.hsplit(h,3)
print("hsplit:",h_split)

#vsplit(): Splits an array vertically (along rows).
v_split=np.vsplit(h,2)
print("vsplit:",v_split)

hsplit: [array([[12, 23],
       [23, 34]]), array([[56, 67],
       [78, 89]]), array([[32, 43],
       [54, 65]])]
vsplit: [array([[12, 23, 56, 67, 32, 43]]), array([[23, 34, 78, 89, 54, 65]])]


In [15]:
print(a.max())# its show max value in array

5


In [16]:
print(a.min())#its show min value in array

1


In [17]:
print(np.std(a))# its return standerd devision

1.4142135623730951


In [18]:
arr=np.arange(0,20,2,float)
print(arr)
print(arr.dtype)# datatype define karyu

[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18.]
float64


In [19]:
#Creates an array with evenly spaced values.
a=np.linspace(0,20,11)
print(a)

[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]
